name: flowise-ai-tutorial
services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/flowise_data:/root/.flowise
    environment:
      - PORT=3000
      - DATABASE_PATH=/root/.flowise/flowise.db
    restart: unless-stopped
    depends_on:
      - qdrant
      # - localai

  # ##################################################################
  # Qdrant: Vector Database
  # Visualize: http://localhost:6333/dashboard
  # ##################################################################
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: "mysecretapikey"
    restart: unless-stopped

  # localai:
  #   container_name: local-ai
  #   hostname: local-ai
  #   image: docker.io/localai/localai:v2.10.1
  #   platform: linux/amd64
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MODELS_PATH=/models
  #     - API_KEY='somevaluehere'
  #   volumes:
  #     - ./volumes/localai/models:/models
  #   command:
  #     - phi-2